version: 2

project_name: corg

before:
  hooks:
    - go mod download

builds:
  - id: corg
    main: ./cmd/kubectl-corg
    binary: corg
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags:
      - -s -w -X github.com/clevyr/borgbase-operator/internal/cli.version={{ .Version }}

archives:
  - id: corg
    ids: [corg]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    formats: [tar.gz]
    files:
      - README.md

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true

homebrew_casks:
  - name: corg
    ids: [corg]
    repository:
      owner: clevyr
      name: homebrew-tap
    homepage: https://github.com/clevyr/borgbase-operator
    description: Companion CLI for the Clevyr borgbase operator
    binaries: [corg]
    custom_block: |
      binary "corg", target: "kubectl-corg"
    hooks:
      post:
        install: |
          if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/corg"]
          end

release:
  prerelease: auto
