apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: borgbase-operator
    app.kubernetes.io/managed-by: kustomize
  name: corg-viewer
rules:
  - apiGroups:
      - borgbase.clevyr.com
    resources:
      - repositories
      - scheduledbackups
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - borgbase.clevyr.com
    resources:
      - repositories/status
      - scheduledbackups/status
    verbs:
      - get
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: borgbase-operator
    app.kubernetes.io/managed-by: kustomize
  name: corg-operator
rules:
  - apiGroups:
      - borgbase.clevyr.com
    resources:
      - repositories
      - scheduledbackups
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - borgbase.clevyr.com
    resources:
      - repositories/status
      - scheduledbackups/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - patch
      - update
      - delete
