resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- metrics_auth_role.yaml
- metrics_auth_role_binding.yaml
- metrics_reader_role.yaml
- scheduledbackup_admin_role.yaml
- scheduledbackup_editor_role.yaml
- scheduledbackup_viewer_role.yaml
- repository_admin_role.yaml
- repository_editor_role.yaml
- repository_viewer_role.yaml
- corg_user_role.yaml
