apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: borgbase-operator
    app.kubernetes.io/managed-by: kustomize
  name: scheduledbackup-admin-role
rules:
- apiGroups:
  - borgbase.clevyr.com
  resources:
  - scheduledbackups
  verbs:
  - '*'
- apiGroups:
  - borgbase.clevyr.com
  resources:
  - scheduledbackups/status
  verbs:
  - get
