package cli

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/spf13/cobra"
	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/yaml"

	borgbasev1 "github.com/clevyr/borgbase-operator/api/v1"
)

var (
	ErrNoRepositoryID = errors.New("could not recover the BorgBase repository ID")
	ErrExcludeCount   = errors.New("refusing to emit a partial exclude list")
)

// migratedName is what the generated resources are called. The hand-written
// backups are all deployed under this name.
const migratedName = "restic"

// repositoryIDPattern matches the id the CRD will accept.
var repositoryIDPattern = regexp.MustCompile(`^[a-z0-9]{4,32}$`)

func newMigrateCommand(f *Factory) *cobra.Command {
	var repositoryID string

	cmd := &cobra.Command{
		Use:     "migrate <resources/restic directory>",
		Short:   "Generate resources from a hand-written backup",
		GroupID: GroupDevelopment,
		Long: `Convert an app's hand-written restic backup into operator resources.

Reads the HelmRelease and emits a Repository and a ScheduledBackup on stdout.
Nothing is applied and nothing in fleet-infra is modified; diff the output
against the HelmRelease, then check it with corg parity.

The BorgBase repository ID is recorded only inside the encrypted
RESTIC_REPOSITORY value. By default corg decrypts secret.yaml by running sops,
which is where the cloud credentials for that live. Pass --repository-id to
skip decryption entirely.

Before applying, reduce the app's secret.yaml to just RESTIC_PASSWORD:
RESTIC_REPOSITORY is synthesized by the operator and CHECK_UUID is replaced by
healthchecks slug pinging. Do not remove RESTIC_PASSWORD -- it is the only
off-cluster copy of the key that decrypts these backups.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runMigrate(f.Streams.Out, args[0], repositoryID)
		},
	}

	cmd.Flags().StringVar(&repositoryID, "repository-id", "",
		"Use this BorgBase repository ID instead of decrypting secret.yaml")
	return cmd
}

func runMigrate(out io.Writer, dir, repositoryID string) error {
	helmReleasePath := filepath.Join(dir, "helmrelease.yaml")
	if _, err := os.Stat(helmReleasePath); err != nil {
		return fmt.Errorf("no helmrelease.yaml in %s", dir)
	}

	hr, err := readHelmRelease(helmReleasePath)
	if err != nil {
		return err
	}

	if repositoryID == "" {
		if repositoryID, err = repositoryIDFromSecret(filepath.Join(dir, "secret.yaml")); err != nil {
			return err
		}
	}
	if !repositoryIDPattern.MatchString(repositoryID) {
		return fmt.Errorf("%w: %q is not a BorgBase repository ID", ErrNoRepositoryID, repositoryID)
	}

	repo, sb, err := migrateHelmRelease(hr, repositoryID)
	if err != nil {
		return err
	}

	p := newPrinter(out)
	p.printf("# Generated by corg migrate from %s\n", helmReleasePath)
	p.println("# Review against the HelmRelease, then check it with corg parity.")

	// The resources are marshalled from typed objects, which cannot carry
	// comments, so the provenance of a converted schedule goes in the header.
	// A reviewer needs to see what it was to judge whether it should have been
	// converted at all.
	if original := hr.scheduleOf(); original != sb.Spec.Schedule {
		p.println("#")
		p.printf("# schedule: was %q, hand-jittered. Handed back to the operator as %q,\n",
			original, sb.Spec.Schedule)
		p.println("# which derives its own minute from a hash of this resource, so the")
		p.println("# spread is kept without anyone maintaining it. Check")
		p.println("# status.effectiveSchedule for the expression it settles on.")
	}
	if err := p.Err(); err != nil {
		return err
	}
	return writeDocuments(out, repo, sb)
}

// writeDocuments marshals the generated resources.
//
// They are emitted from the real API types rather than assembled as text, so
// the output cannot be shaped in a way the CRDs would reject.
func writeDocuments(out io.Writer, objects ...any) error {
	p := newPrinter(out)
	for i, obj := range objects {
		data, err := yaml.Marshal(obj)
		if err != nil {
			return err
		}
		if i > 0 {
			p.println("---")
		}
		p.print(string(data))
	}
	return p.Err()
}

func migrateHelmRelease(
	hr *helmRelease, repositoryID string,
) (*borgbasev1.Repository, *borgbasev1.ScheduledBackup, error) {
	namespace := hr.Metadata.Namespace

	controller, container, err := hr.backupController()
	if err != nil {
		return nil, nil, err
	}
	script, err := container.script()
	if err != nil {
		return nil, nil, err
	}

	sources, retention, engine, err := parseBackupScript(script)
	if err != nil {
		return nil, nil, err
	}

	repo := &borgbasev1.Repository{
		APIVersion: borgbasev1.SchemeGroupVersion.String(), Kind: "Repository",
		Namespace: namespace, Name: migratedName,
		Spec: borgbasev1.RepositorySpec{
			ExistingRepositoryID: repositoryID,
			PasswordSecretRef: &corev1.SecretKeySelector{
				Name: "restic-envs",
				Key:  "RESTIC_PASSWORD",
			},
		},
	}

	sb := &borgbasev1.ScheduledBackup{
		APIVersion: borgbasev1.SchemeGroupVersion.String(), Kind: "ScheduledBackup",
		Namespace: namespace, Name: migratedName,
		Spec: borgbasev1.ScheduledBackupSpec{
			RepositoryRef: corev1.LocalObjectReference{Name: migratedName},
			Schedule:      shorthandSchedule(controller.CronJob.Schedule),
			Sources:       sources,
			Retention:     retention,
			Healthchecks: &borgbasev1.HealthchecksSpec{
				PingKeySecretRef: &corev1.SecretKeySelector{
					Name: "healthchecks-ping-key",
					Key:  "PING_KEY",
				},
			},
		},
	}

	if p := controller.CronJob.ConcurrencyPolicy; p != "" {
		sb.Spec.ConcurrencyPolicy = batchv1.ConcurrencyPolicy(p)
	}
	// The CronJob's time zone decides what a pinned schedule means, and the CRD
	// defaults it, so an app on anything else has to carry it across.
	if tz := controller.CronJob.TimeZone; tz != "" {
		sb.Spec.TimeZone = tz
	}

	if engine != "" {
		db := &borgbasev1.DatabaseSpec{Engine: engine}
		db.SecretName = hr.databaseSecret()
		db.Host = container.env("DB_HOST")
		db.Name = container.env("DB_DATABASE")
		db.User = container.env("DB_USERNAME")
		sb.Spec.Database = db
	}

	if claim := hr.existingClaim(); claim != "" {
		volume := &borgbasev1.VolumeSpec{ExistingClaim: claim}
		// workingDir defaults to /<claim>; only carry a mountPath that differed.
		if wd := container.WorkingDir; wd != "" && wd != "/"+claim {
			volume.MountPath = wd
		}
		sb.Spec.Volume = volume
	}

	if class := hr.cacheStorageClass(); class != "" {
		sb.Spec.Cache = &borgbasev1.CacheSpec{StorageClass: class}
	}

	return repo, sb, nil
}

// parseBackupScript reads the sources and retention out of a hand-written
// backup script.
//
// It tokenises each restic invocation rather than matching patterns across the
// whole script, so a quoted exclude containing a space stays one pattern and a
// second database source is not confused with the first.
func parseBackupScript(script string) (
	[]borgbasev1.BackupSource, *borgbasev1.Retention, borgbasev1.DatabaseEngine, error,
) {
	var sources []borgbasev1.BackupSource
	var retention *borgbasev1.Retention
	var engine borgbasev1.DatabaseEngine

	for _, line := range joinContinuations(script) {
		args := splitArgs(line)
		if len(args) < 2 || args[0] != "restic" {
			continue
		}

		switch args[1] {
		case "backup":
			source, sourceEngine, err := parseBackupLine(args)
			if err != nil {
				return nil, nil, "", err
			}
			if sourceEngine != "" {
				engine = sourceEngine
			}
			sources = append(sources, source)
		case "forget":
			r, err := parseRetention(args)
			if err != nil {
				return nil, nil, "", err
			}
			retention = r
		}
	}

	return sources, retention, engine, nil
}

func parseBackupLine(args []string) (borgbasev1.BackupSource, borgbasev1.DatabaseEngine, error) {
	var source borgbasev1.BackupSource
	if tag, ok := flagValue(args, "tag"); ok {
		source.Tag = tag
	}

	// A database source pipes a dump in: `--stdin-from-command -- dumpdb ENGINE`.
	if i := indexOf(args, "--stdin-from-command"); i >= 0 {
		engine, rest, err := parseDumpdb(args[i:])
		if err != nil {
			return source, "", err
		}
		source.Type = borgbasev1.SourceType(engine)
		if database, ok := flagValue(rest, "database"); ok {
			source.Database = database
		}
		// Anything after a second `--` is passed through to the client.
		if extra := passthrough(rest); len(extra) > 0 {
			source.ExtraArgs = extra
		}
		return source, engine, nil
	}

	source.Type = borgbasev1.SourceTypeFiles
	source.Path = firstPositional(args[2:])

	excludes := flagValues(args, "exclude")
	// Counting them separately catches a pattern the tokeniser lost, which
	// would silently widen what gets backed up.
	if want := strings.Count(strings.Join(args, " "), "--exclude="); want != len(excludes) {
		return source, "", fmt.Errorf("%w: parsed %d of %d --exclude patterns",
			ErrExcludeCount, len(excludes), want)
	}
	source.Exclude = excludes

	return source, "", nil
}

// parseDumpdb reads the engine out of `-- dumpdb ENGINE ...`.
func parseDumpdb(args []string) (borgbasev1.DatabaseEngine, []string, error) {
	for i := range args {
		if args[i] != "dumpdb" || i+1 >= len(args) {
			continue
		}
		switch engine := args[i+1]; engine {
		case string(borgbasev1.DatabaseEngineCNPG), string(borgbasev1.DatabaseEngineMariaDB):
			return borgbasev1.DatabaseEngine(engine), args[i+2:], nil
		default:
			return "", nil, fmt.Errorf("unrecognised dumpdb engine %q", engine)
		}
	}
	return "", nil, errors.New("a --stdin-from-command backup with no dumpdb invocation")
}

// passthrough returns the arguments after a bare `--`.
func passthrough(args []string) []string {
	if i := indexOf(args, "--"); i >= 0 && i+1 < len(args) {
		return args[i+1:]
	}
	return nil
}

func parseRetention(args []string) (*borgbasev1.Retention, error) {
	r := &borgbasev1.Retention{}
	fields := map[string]**int32{
		"last": &r.Last, "hourly": &r.Hourly, "daily": &r.Daily,
		"weekly": &r.Weekly, "monthly": &r.Monthly, "yearly": &r.Yearly,
	}

	found := false
	for unit, target := range fields {
		value, ok := flagValue(args, "keep-"+unit)
		if !ok {
			continue
		}
		n, err := parseInt32(value)
		if err != nil {
			return nil, fmt.Errorf("--keep-%s=%s: %w", unit, value, err)
		}
		*target = n
		found = true
	}
	if !found {
		return nil, nil
	}
	return r, nil
}

// shorthandSchedule hands a hand-jittered expression back to the operator.
//
// The hand-written schedules are hand-jittered, and copy-paste means several
// apps share a minute. Converting the shapes that map exactly lets the operator
// derive the offset from a hash of the resource, so the spread is maintained
// without anyone maintaining it. Anything else is pinned verbatim, since a
// schedule nobody can read is not worth guessing at.
func shorthandSchedule(expr string) string {
	fields := strings.Fields(expr)
	if len(fields) != 5 {
		return expr
	}
	minute, hour := fields[0], fields[1]
	if fields[2] != "*" || fields[3] != "*" || fields[4] != "*" {
		return expr
	}
	if !isNumeric(minute) {
		return expr
	}

	switch {
	case hour == "*":
		return "@hourly"
	case isNumeric(hour):
		return "@daily"
	default:
		if step, ok := strings.CutPrefix(hour, "*/"); ok && isNumeric(step) {
			return "@every " + step + "h"
		}
	}
	return expr
}

func isNumeric(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}
	return true
}

func indexOf(args []string, want string) int {
	for i, a := range args {
		if a == want {
			return i
		}
	}
	return -1
}

// firstPositional returns the first argument that is not a flag, which for a
// files backup is the path.
func firstPositional(args []string) string {
	for _, a := range args {
		if !strings.HasPrefix(a, "-") {
			return a
		}
	}
	return ""
}
