apiVersion: borgbase.clevyr.com/v1
kind: Repository
metadata:
  name: restic
  namespace: myapp-prod
spec:
  existingRepositoryID: a1b2c3d4
  passwordSecretRef:
    name: restic-envs
    key: RESTIC_PASSWORD
---
apiVersion: borgbase.clevyr.com/v1
kind: Repository
metadata:
  name: restic
  namespace: otherapp-prod
spec:
  region: us
  quotaGiB: 100
  alertDays: 3
