apiVersion: borgbase.clevyr.com/v1
kind: ScheduledBackup
metadata:
  labels:
    app.kubernetes.io/name: borgbase-operator
    app.kubernetes.io/managed-by: kustomize
  name: scheduledbackup-sample
spec:
  # TODO(user): Add fields here
