apiVersion: borgbase.clevyr.com/v1
kind: ScheduledBackup
metadata:
  name: restic
  namespace: myapp-prod
spec:
  repositoryRef:
    name: restic
  schedule: "@hourly"
  sources:
    - type: cnpg
      tag: db
    - type: files
      tag: files
      path: app
      exclude:
        - "**/temp*"
        - app/export-logs
  retention:
    hourly: 168
    daily: 90
    monthly: 24
    yearly: 10
  database:
    engine: cnpg
    secretName: postgresql-app
  volume:
    existingClaim: myapp-prod-storage
  cache:
    storageClass: nfs-regional-ssd
  healthchecks:
    pingKeySecretRef:
      name: healthchecks-ping-key
      key: PING_KEY
---
apiVersion: borgbase.clevyr.com/v1
kind: ScheduledBackup
metadata:
  name: restic
  namespace: otherapp-prod
spec:
  repositoryRef:
    name: restic
  schedule: "20 0 * * *"
  concurrencyPolicy: Replace
  sources:
    - type: mariadb
      tag: db
      extraArgs: ["--skip-ssl"]
    - type: files
      tag: files
      exclude: [dumps]
  retention:
    daily: 90
    monthly: 24
    yearly: 10
  database:
    engine: mariadb
    secretName: mariadb
    host: mariadb
    name: appdb
    user: appdb
  volume:
    existingClaim: otherapp-prod-data
  cache:
    storageClass: nfs-regional-ssd
  healthchecks:
    pingKeySecretRef:
      name: healthchecks-ping-key
      key: PING_KEY
