resources:
- bases/borgbase.clevyr.com_repositories.yaml
- bases/borgbase.clevyr.com_scheduledbackups.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# +kubebuilder:scaffold:crdkustomizewebhookpatch
